### ISSUE TITLE
Identical twins and NGSCheckMate

### ISSUE THREAD

**Issue by ManavalanG** [parklab/NGSCheckMate#19]
Hi, how well does NGSCheckMate deal with identical twins? In my attempt, it could not differentiate between WGS from two identical twins.

**Comment by sejooning** [comment]
Hi, ManavalanG.

Thank you for the very interesting question. We have not attempted to differentiate between NGS from two identical twins, I think that NGSCheckMate is not able to distinguish the identical twins because their SNPs are almost the same except for some de novo variations.

Thanks,
Sejoon Lee

**Comment by ManavalanG** [comment]
Thanks @sejooning!
