### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by cramirezs** [parklab/NGSCheckMate#4]
Hello, I have a set of vcf files and I am trying to use your software to check how many groups I have in my data. It is single-cell data and what I want to do exactly is compare my genotype data in each cell to every donor and determine what donor they come from.

I'm copying the issue:

Traceback (most recent call last):
  File "/home/ciro/bin/NGSCheckMate/ncm.py", line 1461, in <module>
    classifying()
  File "/home/ciro/bin/NGSCheckMate/ncm.py", line 905, in classifying
    distance = pearson_def(vecA, vecB)
  File "/home/ciro/bin/NGSCheckMate/ncm.py", line 59, in pearson_def
    return diffprod / math.sqrt(xdiff2 * ydiff2)
ZeroDivisionError: float division by zero

Thank you very much,
Ciro

**Comment by cramirezs** [comment]
Hi again,

Now I called my SNPs with [Freebayes](https://github.com/ekg/freebayes) but still find another error:

Traceback (most recent call last):
  File "/home/ciro/bin/NGSCheckMate/ncm.py", line 1460, in <module>
    createDataSetFromDir(base_dir,bedFile)
  File "/home/ciro/bin/NGSCheckMate/ncm.py", line 220, in createDataSetFromDir
    real_depth[file] = depth[file] / float(real_count[file])
ZeroDivisionError: float division by zero

Let me know if you need any further details.

**Comment by sejooning** [comment]
Hello, Mr. Ciro, 

I think there are two possibilities about errors which you mentioned.
 1) the number of genotyped loci is too small so that there may be few or nothing SNPs which we are using for calculating a correlation.
 2) for the two sample comparison, there may be no overlapped loci between two samples, when the number of genotypes loci is too small even they have a few SNPs which we used for calculating a correlation.

Both of cases are due to the very low coverage (Calculating an average coverage of 21,067 SNPs), We could not apply NGSCheckMate to those samples, so we should remove those samples from the input set now.

Thank you, 
Best,
SJ

**Comment by cramirezs** [comment]
Hello,

Is there a way to

Thank you for the answer,
Ciro
